### GET request to example server
GET http://localhost:8080

### GET request to display all note files data
GET http://localhost:8080/api/v1/note-file

### GET request to display note files data by id
GET http://localhost:8080/api/v1/note-file/2

### DELETE request to delete note files data by id
DELETE http://localhost:8080/api/v1/note-file/1

### POST request to insert note files data
POST http://localhost:8080/api/v1/note-file
Content-Type: application/json

{
  "filename": "My First Note",
  "content": "This is the content of my first note.",
  "pinned": false,
  "sourceUrl": "https://example1.com"
}

### PUT request to update an existing note file by id
PUT http://localhost:8080/api/v1/note-file/3
Content-Type: application/json

{
  "filename": "Updated Note Title",
  "content": "This is the updated content of my note.",
  "pinned": true,
  "sourceUrl": "https://updated-example.com"
}
